# Generated by Django 5.0.6 on 2024-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_pedido_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En Preparación'), ('despacho', 'En Despacho'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
