# Generated by Django 5.0.6 on 2024-05-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_pedido_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
